### ISSUE TITLE
SyntaxError: Unexpected token )

### ISSUE THREAD

**Issue by darrenjennings** [kentcdodds/generator-kcd-oss#6]
I just installed the tool and when I ran the command for the first time:

```
% yo kcd-oss
```

```
/usr/local/lib/node_modules/generator-kcd-oss/generators/app/index.js:33
      )
      ^
SyntaxError: Unexpected token )
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as kcd-oss:app] (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:38:27)
```

https://github.com/kentcdodds/generator-kcd-oss/blob/2c79f46864208be99b028d0cf58a826192a6199b/generators/app/index.js#L29-L33

Node version: `v7.10.1`
Npm version: `4.2.0`

**Comment by ijones16** [comment]
Hey @darrenjennings,

I just ran into this issue. It is because [kcd-scripts](https://github.com/kentcdodds/kcd-scripts/blob/master/package.json#L6) requires you to use Node >= 8.  I was on v7.4 and upgraded to v8.7 and the issue was resolved.

Hope this helps!

Cheers

**Comment by kentcdodds** [comment]
Actually, I realized that this is a different issue @ijones16. Same error message, but different issue.

I'm not going to fix the one here because this repository is for me and I don't officially care to support other use cases. I'll always have node v8 when running this.

So you can install node@8 and use that to use this package. Good luck! Thanks.
